[server]
bind-address=":8080"
mode="debug"  # GIN mode. Either debug, release or test
boiler-mode="debug"  # Either debug or something else.
rollbar-token=""
rollbar-environment="development"
http-pprof-pass=""
log-level="info" # One of: panic, fatal, error, warn, info, debug, trace.

[mdb]
url="postgres://localhost/mdb?sslmode=disable&user=postgres"

[test]
enable-online-eval=false
search-data="./search/data/"
test-source-content-docx="$GOPATH/src/github.com/Bnei-Baruch/archive-backend/es/TEST-CONTENT.docx"
test-sources-folder="/tmp/test-sources-folder"
mdb-url="postgres://localhost/mdb?sslmode=disable&user=postgres"
url-template="postgres://localhost/%s?sslmode=disable&user=postgres"
#for windows:
#test-source-content-docx="C://Users//[USERNAME]//go//src//github.com//Bnei-Baruch//archive-backend//es//TEST-CONTENT.docx"
#test-sources-folder="C://test-sources-folder"

[elasticsearch]
url="http://127.0.0.1:9200"
data-folder="/tmp/search-data"  # At repo, see: ./data
sources-folder="/tmp/sources-folder"
unzip-url=""
prepare-docs-batch-size=20
prepare-docs-parallelism=2
#index-date = "2018-11-28t13:08:31-05:00" # optional, NOT FOR PRODUCTION, comment out to use alias.
#grammar-index-date = "2018-11-28t13:08:31-05:00" # optional, NOT FOR PRODUCTION, comment out to use alias.
check-typo=true
timeout-for-highlight="8s"

[nats]
url="nats://localhost:4222"

[file_service]
url1="http://files.kabbalahmedia.info/api/v1/get"

[assets_service]
url="https://kabbalahmedia.info/assets/api/"

[feed_service]
url="https://kabbalahmedia.info/feed_api/"

[content_unit_images]
url_template="https://kabbalahmedia.info/imaginary/thumbnail?url=http%%3A%%2F%%2Fnginx%%2Fassets%%2Fapi%%2Fthumbnail%%2F%s&width=140&stripmeta=true"

[cache]
refresh-search-stats="5m"
