[mdb]
url="postgres://localhost/mdb?sslmode=disable&user=postgres"

[test]
mdb-url="postgres://localhost/mdb?sslmode=disable&user=postgres"
url-template="postgres://localhost/%s?sslmode=disable&user=postgres"

[elasticsearch]
url="http://127.0.0.1:9200"
docx-folder="/tmp/mdb-docx/"
soffice-bin="/usr/bin/soffice"

[server]
bind-address=":8080"
mode="debug"  # GIN mode. Either debug, release or test
boiler-mode="debug"  # Eigher debug or something else.
rollbar-token=""
rollbar-environment="development"

[links]
bind-address=":8081"
mode="debug"  # GIN mode. Either debug, release or test
rollbar-token=""
rollbar-environment="development"

[file_service]
url1="http://files.kabbalahmedia.info/api/v1/get"
url2="http://files.kabbalahmedia.info/api/v1/get"

[nats]
url="nats://localhost:4222"
client-id="my-sample-nats-client"
cluster-id="my-nats-cluster-id"
subject="subject"
durable=false
durable-name="test-name" # name for durable subscribtion meaning it will start from where it finished last time