[server]
bind-address=":8080"
mode="debug"  # GIN mode. Either debug, release or test
boiler-mode="debug"  # Eigher debug or something else.
rollbar-token=""
rollbar-environment="development"

[mdb]
url="postgres://localhost/mdb?sslmode=disable&user=postgres"
#os="windows"

[test]
test-docx-folder="es/testdocx"
#for windows:
#test-docx-folder="C://Users//[USERNAME]//go//src//github.com//Bnei-Baruch//archive-backend//es//testdocx"

[elasticsearch]
url="http://127.0.0.1:9200"
parse-docs-bin="es/parse_docs.py"
docx-folder="/tmp/mdb-docx/"
soffice-bin="/usr/bin/soffice"
#for windows:
#soffice-bin="C://Program Files//LibreOffice 5//program//soffice.exe"
#parse-docs-bin = "C://Users//[USERNAME]//go//src//github.com//Bnei-Baruch//archive-backend//es//parse_docs.py"
#python-path="C://Python27//python.exe"
cdn-url=""

[nats]
url="nats://localhost:4222"
client-id="my-sample-nats-client"
cluster-id="my-nats-cluster-id"
subject="subject"
durable=false
durable-name="test-name" # name for durable subscribtion meaning it will start from where it finished last time

[file_service]
url1="http://files.kabbalahmedia.info/api/v1/get"

[assets_service]
url="https://archive.kbb1.com/assets/api/"

[test]
mdb-url="postgres://localhost/mdb?sslmode=disable&user=postgres"
url-template="postgres://localhost/%s?sslmode=disable&user=postgres"
test-docx-folder="/home/kolmanv/mdb-docx-test/"
test-cdn-url="http://localhost"
