version: '3'

services:
  elastic:
    image: bneibaruch/docker-files:archive-elasticsearch
    environment:
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      bootstrap.system_call_filter: "false"
    ports:
      - 9200:9200
      - 9300:9300

  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mdb
    ports:
      - 5432:5432
