version: '3'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      discovery.type: "single-node"
    ports:
      - 9200:9200
      - 9300:9300

  db:
    image: postgres:9
    restart: always
    environment:
      POSTGRES_DB: mdb
    ports:
      - 5432:5432
