package api

import "github.com/Bnei-Baruch/archive-backend/mdb"

const (
	DEFAULT_PAGE_SIZE = 50
	MAX_PAGE_SIZE     = 1000
)

var LANG_ORDER = map[string][]string{
	"":                  {mdb.LANG_ENGLISH},
	mdb.LANG_ENGLISH:    {mdb.LANG_ENGLISH},
	mdb.LANG_HEBREW:     {mdb.LANG_HEBREW, mdb.LANG_ENGLISH},
	mdb.LANG_RUSSIAN:    {mdb.LANG_RUSSIAN, mdb.LANG_ENGLISH},
	mdb.LANG_SPANISH:    {mdb.LANG_SPANISH, mdb.LANG_ENGLISH},
	mdb.LANG_ITALIAN:    {mdb.LANG_ITALIAN, mdb.LANG_ENGLISH},
	mdb.LANG_GERMAN:     {mdb.LANG_GERMAN, mdb.LANG_ENGLISH},
	mdb.LANG_DUTCH:      {mdb.LANG_DUTCH, mdb.LANG_ENGLISH},
	mdb.LANG_FRENCH:     {mdb.LANG_FRENCH, mdb.LANG_ENGLISH},
	mdb.LANG_PORTUGUESE: {mdb.LANG_PORTUGUESE, mdb.LANG_ENGLISH},
	mdb.LANG_TURKISH:    {mdb.LANG_TURKISH, mdb.LANG_ENGLISH},
	mdb.LANG_POLISH:     {mdb.LANG_POLISH, mdb.LANG_ENGLISH},
	mdb.LANG_ARABIC:     {mdb.LANG_ARABIC, mdb.LANG_ENGLISH},
	mdb.LANG_HUNGARIAN:  {mdb.LANG_HUNGARIAN, mdb.LANG_ENGLISH},
	mdb.LANG_FINNISH:    {mdb.LANG_FINNISH, mdb.LANG_ENGLISH},
	mdb.LANG_LITHUANIAN: {mdb.LANG_LITHUANIAN, mdb.LANG_ENGLISH},
	mdb.LANG_JAPANESE:   {mdb.LANG_JAPANESE, mdb.LANG_ENGLISH},
	mdb.LANG_BULGARIAN:  {mdb.LANG_BULGARIAN, mdb.LANG_ENGLISH},
	mdb.LANG_GEORGIAN:   {mdb.LANG_GEORGIAN, mdb.LANG_ENGLISH},
	mdb.LANG_NORWEGIAN:  {mdb.LANG_NORWEGIAN, mdb.LANG_ENGLISH},
	mdb.LANG_SWEDISH:    {mdb.LANG_SWEDISH, mdb.LANG_ENGLISH},
	mdb.LANG_CROATIAN:   {mdb.LANG_CROATIAN, mdb.LANG_ENGLISH},
	mdb.LANG_CHINESE:    {mdb.LANG_CHINESE, mdb.LANG_ENGLISH},
	mdb.LANG_PERSIAN:    {mdb.LANG_PERSIAN, mdb.LANG_ENGLISH},
	mdb.LANG_ROMANIAN:   {mdb.LANG_ROMANIAN, mdb.LANG_ENGLISH},
	mdb.LANG_HINDI:      {mdb.LANG_HINDI, mdb.LANG_ENGLISH},
	mdb.LANG_UKRAINIAN:  {mdb.LANG_UKRAINIAN, mdb.LANG_ENGLISH},
	mdb.LANG_MACEDONIAN: {mdb.LANG_MACEDONIAN, mdb.LANG_ENGLISH},
	mdb.LANG_SLOVENIAN:  {mdb.LANG_SLOVENIAN, mdb.LANG_ENGLISH},
	mdb.LANG_LATVIAN:    {mdb.LANG_LATVIAN, mdb.LANG_ENGLISH},
	mdb.LANG_SLOVAK:     {mdb.LANG_SLOVAK, mdb.LANG_ENGLISH},
	mdb.LANG_CZECH:      {mdb.LANG_CZECH, mdb.LANG_ENGLISH},
}
